pnpmの指定が必要だったので追加
UsageError: This project is configured to use yarn because /home/runner/work/learning-hasura/learning-hasura/package.json has a "packageManager" field